name: EpicPets
author: Feeps
version: 1.3
main: be.feeps.epicpets.Main
description: Only Feeps know the reals pets
softdepend: [Vault]
commands:
    epicpets:
        usage: /<command>
        description: The epicpets commands
        aliases: [ep, pet, pets, epicpet]